# Generated by Django 5.2.3 on 2025-07-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
    ]
