# Generated by Django 5.2.3 on 2025-07-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_options_rename_date_bid_created_at_and_more'),
    ]

    operations = [
    ]
